/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.Client;

import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author HP
 */
public class AudioInvite extends javax.swing.JDialog {
                private Vector<String> userList;
                private Vector <String> alluserList;
                private Client co; 
                private int roomID;
                private int uID;
                private JComboBox cb;
                private DefaultComboBoxModel model;
    
    
    public AudioInvite(Vector<String> uList,Vector<String> duList,int rID ,Client ClientObject) {
    	userList = uList;
        alluserList = duList;
        co = ClientObject;
        roomID = rID;
    	model = new DefaultComboBoxModel(userList);
    	initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox(model);
        okBu = new javax.swing.JButton();
        cancelBu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        jLabel1.setText("Choose who to speak!");

        comboBox.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        okBu.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        okBu.setText("OK");
        okBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBuActionPerformed(evt);
            }
        });

        cancelBu.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        cancelBu.setText("Cancel");
        cancelBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(okBu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelBu))
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBu)
                    .addComponent(cancelBu))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
         cb =  (JComboBox)evt.getSource();
    }//GEN-LAST:event_comboBoxActionPerformed

    private void okBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBuActionPerformed
    	 //cb =  (JComboBox)evt.getSource();
         String name = (String)cb.getSelectedItem();
         System.out.println("name in invite audio "+name + uID);
         uID = alluserList.indexOf(name);
         co.sendaudio(uID);
         setVisible(false);
    }//GEN-LAST:event_okBuActionPerformed

    private void cancelBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBuActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBuActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBu;
    private javax.swing.JComboBox comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okBu;
    // End of variables declaration//GEN-END:variables
}
