/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Vector;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

import client.Client;

import java.awt.Rectangle;

import gui.InviteFrame;

/**
 *
 * @author HP
 */
public class ChatTab extends javax.swing.JPanel {

        private DefaultListModel<String> ListModel;
        public Vector<String> uList;
        public Vector<String> existList;
        
        private ChatFrame cf;
        private Client ClientObject;
        private MainChatTab mctab;
        
        private int onlineNum;
        private int action;
        public String message;
        private int whisID;
        public int invID;
        public int croomID;
        private boolean whis;
        public String roomName;
	
    public ChatTab(int roomID, MainChatTab Mtab) {
    	//public ChatTab(int roomID){
    	ListModel = new DefaultListModel<String>();
    	initComponents();
    	
        existList = new Vector<String>();
        mctab = Mtab;
        onlineNum = 0;
        croomID = roomID;
        whis = false;
        
    }
    
    public void setFrame(gui.ChatFrame chatF){cf = chatF;}
    public void setClientObject( Client co ) { ClientObject = co; }
   // public void setMCTab(MainChatTab MCTab){mctab = MCTab;}
    
    public void set_Text(String mg){
        SimpleAttributeSet attrset=new SimpleAttributeSet();
         Document docs=textPanel.getDocument();
         
          try{
                docs.insertString(docs.getLength(),mg+"\n",attrset); 
                textPanel.setCaretPosition(textPanel.getDocument().getLength());
             }
          catch(BadLocationException ble){
            System.out.println("BadLocationException:"+ble);	
         }	
    }
    
    public void addUser(String name, int id){
    	System.out.println("addUin_CT " + name + " " + id);
		ListModel.addElement(name);
        existList.add(name);
		onlineNum++;
    }
    
    public void delUser(int id){
    	String name = cf.ouserList.get(id);
   	 	ListModel.removeElement(name);
        int ide = existList.indexOf(name);
   	 	existList.remove(ide);
   	 	onlineNum--; 	 
    }
    
 public void printImage(String image, String name) {
		
		StyledDocument doc = (StyledDocument) textPanel.getDocument();

	    Style style = doc.addStyle("StyleName", null);
	    StyleConstants.setIcon(style, new ImageIcon(image));
	    
	    SimpleAttributeSet attributes = new SimpleAttributeSet();
	    //StyleConstants.setBold(attributes, true);
	    //StyleConstants.setItalic(attributes, true);
	    String s = name + " says: ";

	    try {
	    	doc.insertString(doc.getLength(), s , attributes);
			doc.insertString(doc.getLength(), "Ignore", style);
			set_Text("");
		} catch (BadLocationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}	
	}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<String>(ListModel);
        jScrollPane2 = new javax.swing.JScrollPane();
        textPanel = new javax.swing.JTextPane();
        inviteBu = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        sendFile = new javax.swing.JButton();
        audioBu = new javax.swing.JButton();
        anoy = new javax.swing.JButton();
        smile = new javax.swing.JButton();
        woot = new javax.swing.JButton();
        yeh = new javax.swing.JButton();
        blush = new javax.swing.JButton();
        wave = new javax.swing.JButton();
        unsure = new javax.swing.JButton();
        textField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        leaveBu = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(514, 460));
        setMinimumSize(new java.awt.Dimension(514, 460));
        setPreferredSize(new java.awt.Dimension(514, 460));

        userList.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        userList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userList);

        textPanel.setEditable(false);
        jScrollPane2.setViewportView(textPanel);

        inviteBu.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        inviteBu.setText("invite");
        inviteBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviteBuActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        sendFile.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        sendFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/sendfile1.gif"))); // NOI18N
        sendFile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sendFile.setFocusable(false);
        sendFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sendFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFileActionPerformed(evt);
            }
        });
        jToolBar1.add(sendFile);

        audioBu.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        audioBu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/microphone1.jpg"))); // NOI18N
        audioBu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        audioBu.setFocusable(false);
        audioBu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        audioBu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        audioBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioBuActionPerformed(evt);
            }
        });
        jToolBar1.add(audioBu);

        anoy.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        anoy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/anoy.jpg"))); // NOI18N
        anoy.setFocusable(false);
        anoy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        anoy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        anoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoyActionPerformed(evt);
            }
        });
        jToolBar1.add(anoy);

        smile.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        smile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/smile.jpg"))); // NOI18N
        smile.setFocusable(false);
        smile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        smile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        smile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smileActionPerformed(evt);
            }
        });
        jToolBar1.add(smile);

        woot.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        woot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/woot.jpg"))); // NOI18N
        woot.setFocusable(false);
        woot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        woot.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        woot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wootActionPerformed(evt);
            }
        });
        jToolBar1.add(woot);

        yeh.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        yeh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/yeh.jpg"))); // NOI18N
        yeh.setFocusable(false);
        yeh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        yeh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        yeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yehActionPerformed(evt);
            }
        });
        jToolBar1.add(yeh);

        blush.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        blush.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/blush.gif"))); // NOI18N
        blush.setFocusable(false);
        blush.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        blush.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        blush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blushActionPerformed(evt);
            }
        });
        jToolBar1.add(blush);

        wave.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        wave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/wave.gif"))); // NOI18N
        wave.setFocusable(false);
        wave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        wave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        wave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waveActionPerformed(evt);
            }
        });
        jToolBar1.add(wave);

        unsure.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        unsure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/unsure.gif"))); // NOI18N
        unsure.setFocusable(false);
        unsure.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        unsure.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        unsure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unsureActionPerformed(evt);
            }
        });
        jToolBar1.add(unsure);

        textField.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });

        leaveBu.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        leaveBu.setText("leave");
        leaveBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveBuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(leaveBu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(leaveBu)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textField)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inviteBu, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inviteBu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userListMouseClicked
            if(evt.getClickCount() == 2){
            	Rectangle r = userList. getCellBounds(0,onlineNum-1);
            	if(r!=null && r.contains(evt.getPoint())){
            			String sname = (String )userList.getSelectedValue();
            			whisID = mctab.uList.indexOf(sname);
            			System.out.println(whisID + sname);
            			whis = true;
            		}
                }
    }//GEN-LAST:event_userListMouseClicked

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        String message = textField.getText();
        textField.setText(null);
        if (whis){
            ClientObject.sendWhis(whisID,croomID,message);
            whis = false;
        }
        else
            ClientObject.sendroom(croomID,message);

    }//GEN-LAST:event_textFieldActionPerformed

    private void sendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFileActionPerformed
        ClientObject.sendFile("filename");
    }//GEN-LAST:event_sendFileActionPerformed

    private void anoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoyActionPerformed
        // TODO add your handling code here:
    	ClientObject.sendImage(croomID,"anoy.jpg");
    }//GEN-LAST:event_anoyActionPerformed

    private void smileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smileActionPerformed
        // TODO add your handling code here:
    	ClientObject.sendImage(croomID,"smile.jpg");
    }//GEN-LAST:event_smileActionPerformed

    private void wootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wootActionPerformed
        // TODO add your handling code here:
    	ClientObject.sendImage(croomID,"woot.jpg");
    }//GEN-LAST:event_wootActionPerformed

    private void yehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yehActionPerformed
        // TODO add your handling code here:
    	ClientObject.sendImage(croomID,"yeh.jpg");
    }//GEN-LAST:event_yehActionPerformed

    private void blushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blushActionPerformed
    	ClientObject.sendImage(croomID,"blush.gif");
    }//GEN-LAST:event_blushActionPerformed

    private void audioBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioBuActionPerformed
    	AudioInvite ai = new AudioInvite(mctab.existList,mctab.uList,croomID,ClientObject);
        ai.setVisible(true);
        ai.setModal(true);
    }//GEN-LAST:event_audioBuActionPerformed

    private void waveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waveActionPerformed
    	ClientObject.sendImage(croomID,"wave.gif");
    }//GEN-LAST:event_waveActionPerformed

    private void unsureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unsureActionPerformed
    	ClientObject.sendImage(croomID,"unsure.gif");
    }//GEN-LAST:event_unsureActionPerformed

    private void leaveBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveBuActionPerformed
    	ClientObject.droom(croomID);  
    }//GEN-LAST:event_leaveBuActionPerformed

    
    private void inviteBuActionPerformed(java.awt.event.ActionEvent evt) {                                                
    	InviteFrame iFrame = new InviteFrame(mctab.existList,mctab.uList,this,ClientObject);
    	iFrame.setVisible(true);
    	iFrame.setModal(true);
        
       // ClientObject.addutroom(roomID,);
    }   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anoy;
    private javax.swing.JButton audioBu;
    private javax.swing.JButton blush;
    private javax.swing.JButton inviteBu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton leaveBu;
    private javax.swing.JButton sendFile;
    private javax.swing.JButton smile;
    private javax.swing.JTextField textField;
    private javax.swing.JTextPane textPanel;
    private javax.swing.JButton unsure;
    private javax.swing.JList<String> userList;
    private javax.swing.JButton wave;
    private javax.swing.JButton woot;
    private javax.swing.JButton yeh;
    // End of variables declaration//GEN-END:variables
}
