/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author HP
 */
public class eiconPane extends javax.swing.JDialog {

    /**
     * Creates new form eiconPane
     */
    public eiconPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anoy = new javax.swing.JButton();
        smile = new javax.swing.JButton();
        woot = new javax.swing.JButton();
        yeh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setModal(true);
        anoy.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        anoy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/anoy.jpg"))); // NOI18N
        anoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoyActionPerformed(evt);
            }
        });

        smile.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        smile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/smile.jpg"))); // NOI18N
        smile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smileActionPerformed(evt);
            }
        });

        woot.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        woot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/woot.jpg"))); // NOI18N
        woot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wootActionPerformed(evt);
            }
        });

        yeh.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        yeh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/yeh.jpg"))); // NOI18N
        yeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yehActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anoy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(smile)
                .addGap(18, 18, 18)
                .addComponent(woot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yeh)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anoy)
                    .addComponent(smile)
                    .addComponent(woot)
                    .addComponent(yeh))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoyActionPerformed
       System.out.println("anoy");
        dispose();
    }//GEN-LAST:event_anoyActionPerformed

    private void smileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smileActionPerformed
        System.out.println("smile");
        dispose();
    }//GEN-LAST:event_smileActionPerformed

    private void wootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wootActionPerformed
        System.out.println("woot");
        dispose();
    }//GEN-LAST:event_wootActionPerformed

    private void yehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yehActionPerformed
        System.out.println("yeh");
        dispose();
    }//GEN-LAST:event_yehActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anoy;
    private javax.swing.JButton smile;
    private javax.swing.JButton woot;
    private javax.swing.JButton yeh;
    // End of variables declaration//GEN-END:variables
}
