/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;

import client.Client;

/**
 *
 * @author HP
 */
public class InviteFrame extends JDialog {

		private Vector<String> userList;
		private Vector <String> alluserList;
		private Client co; 
		
		//private String[] exUserList;
		private DefaultComboBoxModel<String> model ;
        private ChatTab invTab;
        private int uID;//selected user ID
        private JComboBox cb;
        private String inviteName;
	
    public InviteFrame(Vector<String> uList,Vector<String> duList, ChatTab tab,Client ClientObject) {   	
    	userList = uList;//online list
    	co = ClientObject; 
    	alluserList = duList;
    	
    	model = new DefaultComboBoxModel(userList);
    	
        initComponents();
        invTab = tab;
    	 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inviteNameComboBox = new javax.swing.JComboBox(model);
        ok_bu = new javax.swing.JButton();
        inviteLabel = new javax.swing.JLabel();
        cancelBu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        
        inviteNameComboBox.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        inviteNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviteNameComboBoxActionPerformed(evt);
            }
        });

        ok_bu.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        ok_bu.setText("OK");
        ok_bu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buActionPerformed(evt);
            }
        });

        inviteLabel.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        inviteLabel.setText("invite");

        cancelBu.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        cancelBu.setText("Cancel");
        cancelBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(inviteLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ok_bu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelBu))
                            .addComponent(inviteNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(inviteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inviteNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_bu)
                    .addComponent(cancelBu))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inviteNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviteNameComboBoxActionPerformed
         cb =  (JComboBox)evt.getSource();
         inviteName = (String)cb.getSelectedItem();
        //String name = (String)cb.getSelectedItem();
        //System.out.println("name in invite "+name + rID);
       // rID = alluserList.indexOf(name);
        
        
    }//GEN-LAST:event_inviteNameComboBoxActionPerformed

    private void ok_buActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buActionPerformed
    	//JComboBox cb =  (JComboBox)evt.getSource(); 
    	
    	if(inviteName == null){
    		inviteName = userList.get(0);
    	}
         System.out.println("name in invite "+inviteName + uID);
         uID = alluserList.indexOf(inviteName);
         System.out.println("alluserList");
    	co.addutroom(invTab.croomID, uID);//not the right one(not the deadlist
    	setVisible(false);
    }//GEN-LAST:event_ok_buActionPerformed

    private void cancelBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBuActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBuActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBu;
    private javax.swing.JLabel inviteLabel;
    private javax.swing.JComboBox inviteNameComboBox;
    private javax.swing.JButton ok_bu;
    // End of variables declaration//GEN-END:variables
}
