/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Vector;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

import client.Client;

import java.awt.Rectangle;

/**
 *
 * @author HP
 */
public class MainChatTab extends javax.swing.JPanel {
	
	private DefaultListModel<String> ListModel;
        public  Vector<String> uList;
        public  Vector<String> existList;
        private ChatFrame cf;
        private Client ClientObject;
        private int onlineNum;
        public String message;
        private boolean whis; 
        private int whisID;
        static public int RoomID = 0;
        
	
    public MainChatTab() {
    	ListModel = new DefaultListModel<String>();
    	initComponents();
    	uList = new Vector<String>();
    	existList = new Vector<String>();
    	
        //uList = ouserList;
        onlineNum = 0;
        whis = false;               
        
    }
    
    public void setFrame(gui.ChatFrame chatF){cf = chatF;}
    public void setClientObject( Client co ) { ClientObject = co; }
    //public void setuList(Vector<String> ouserList) {uList = ouserList;}
    
    public void set_Text(String mg){
        SimpleAttributeSet attrset=new SimpleAttributeSet();
         Document docs=textPanel.getDocument();
         
          try{
                docs.insertString(docs.getLength(),mg+"\n",attrset); 
                textPanel.setCaretPosition(textPanel.getDocument().getLength());
             }
          catch(BadLocationException ble){
            System.out.println("BadLocationException:"+ble);	
         }	
    }

    
	public void getuserList(String name, int id) {
		uList.add(name);
	}
    
    public void addUser(String name, int id){
    	System.out.println("addU " + name + " " + id);
		ListModel.addElement(name);
		existList.add(name);
		onlineNum++;
    }
    
    public void delUser(int id){    	
        String name = uList.get(id);
        System.out.println("delU" + name + id);
   	 	ListModel.removeElement(name);
   	 	int idx = existList.indexOf(name);
   	 	existList.remove(idx);
   	 	onlineNum--; 	 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPanel = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<String>(ListModel);
        toolBar = new javax.swing.JToolBar();
        sendFile = new javax.swing.JButton();
        audioBu = new javax.swing.JButton();
        anoy = new javax.swing.JButton();
        smile = new javax.swing.JButton();
        woot = new javax.swing.JButton();
        yeh = new javax.swing.JButton();
        blush = new javax.swing.JButton();
        wave = new javax.swing.JButton();
        unsure = new javax.swing.JButton();
        textField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setMaximumSize(new java.awt.Dimension(514, 460));
        setMinimumSize(new java.awt.Dimension(514, 460));
        setPreferredSize(new java.awt.Dimension(514, 460));

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(376, 286));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(376, 286));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(376, 286));

        textPanel.setEditable(false);
        textPanel.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        textPanel.setMaximumSize(new java.awt.Dimension(376, 286));
        textPanel.setMinimumSize(new java.awt.Dimension(376, 286));
        textPanel.setPreferredSize(new java.awt.Dimension(376, 286));
        jScrollPane1.setViewportView(textPanel);

        userList.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        userList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(userList);

        toolBar.setRollover(true);

        sendFile.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        sendFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/sendfile1.gif"))); // NOI18N
        sendFile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sendFile.setFocusable(false);
        sendFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sendFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFileActionPerformed(evt);
            }
        });
        toolBar.add(sendFile);

        audioBu.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        audioBu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/microphone1.jpg"))); // NOI18N
        audioBu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        audioBu.setFocusable(false);
        audioBu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        audioBu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        audioBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioBuActionPerformed(evt);
            }
        });
        toolBar.add(audioBu);

        anoy.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        anoy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/anoy.jpg"))); // NOI18N
        anoy.setFocusable(false);
        anoy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        anoy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        anoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoyActionPerformed(evt);
            }
        });
        toolBar.add(anoy);

        smile.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        smile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/smile.jpg"))); // NOI18N
        smile.setFocusable(false);
        smile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        smile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        smile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smileActionPerformed(evt);
            }
        });
        toolBar.add(smile);

        woot.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        woot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/woot.jpg"))); // NOI18N
        woot.setFocusable(false);
        woot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        woot.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        woot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wootActionPerformed(evt);
            }
        });
        toolBar.add(woot);

        yeh.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        yeh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/yeh.jpg"))); // NOI18N
        yeh.setFocusable(false);
        yeh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        yeh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        yeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yehActionPerformed(evt);
            }
        });
        toolBar.add(yeh);

        blush.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        blush.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/blush.gif"))); // NOI18N
        blush.setFocusable(false);
        blush.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        blush.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        blush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blushActionPerformed(evt);
            }
        });
        toolBar.add(blush);

        wave.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        wave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/wave.gif"))); // NOI18N
        wave.setFocusable(false);
        wave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        wave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        wave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waveActionPerformed(evt);
            }
        });
        toolBar.add(wave);

        unsure.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        unsure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/unsure.gif"))); // NOI18N
        unsure.setFocusable(false);
        unsure.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        unsure.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        unsure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unsureActionPerformed(evt);
            }
        });
        toolBar.add(unsure);

        textField.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        textField.setMaximumSize(new java.awt.Dimension(376, 117));
        textField.setMinimumSize(new java.awt.Dimension(376, 117));
        textField.setPreferredSize(new java.awt.Dimension(376, 23));
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        String message = textField.getText();
        textField.setText(null);
        if (whis){
            ClientObject.sendWhis(whisID,0,message);
            whis = false;
        }
        else
            ClientObject.sendall(message);

    }//GEN-LAST:event_textFieldActionPerformed

    private void userListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userListMouseClicked
            if(evt.getClickCount() == 2){
            Rectangle r = userList. getCellBounds(0,onlineNum-1);
            System.out.println("onlineNum: " + onlineNum);
            if(r!=null && r.contains(evt.getPoint())){
            String sname = (String )userList.getSelectedValue();
            whisID = uList.indexOf(sname);
            System.out.println(whisID + sname);
            whis = true;
            }
                    }
    }//GEN-LAST:event_userListMouseClicked

    private void sendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFileActionPerformed
        ClientObject.sendFile("filename");
    }//GEN-LAST:event_sendFileActionPerformed

    private void anoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoyActionPerformed
        // TODO add your handling code here:
    	ClientObject.sendImage(0,"anoy.jpg");
    }//GEN-LAST:event_anoyActionPerformed

    private void smileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smileActionPerformed
        // TODO add your handling code here:
    	ClientObject.sendImage(0,"smile.jpg");
    }//GEN-LAST:event_smileActionPerformed

    private void wootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wootActionPerformed
        // TODO add your handling code here:
    	ClientObject.sendImage(0,"woot.jpg");
    }//GEN-LAST:event_wootActionPerformed

    private void yehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yehActionPerformed
        // TODO add your handling code here:
    	ClientObject.sendImage(0,"yeh.jpg");
    }//GEN-LAST:event_yehActionPerformed

    private void blushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blushActionPerformed
    	ClientObject.sendImage(0,"blush.gif");
    }//GEN-LAST:event_blushActionPerformed

    private void waveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waveActionPerformed
    	ClientObject.sendImage(0,"wave.gif");
    }//GEN-LAST:event_waveActionPerformed

    private void unsureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unsureActionPerformed
    	ClientObject.sendImage(0,"unsure.gif");
    }//GEN-LAST:event_unsureActionPerformed

    private void audioBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioBuActionPerformed
        AudioInvite ai = new AudioInvite(existList,uList,0,ClientObject);
        ai.setVisible(true);
        ai.setModal(true);
    }//GEN-LAST:event_audioBuActionPerformed

    public void printImage(String image, String name) {
		
		StyledDocument doc = (StyledDocument) textPanel.getDocument();

	    Style style = doc.addStyle("StyleName", null);
	    StyleConstants.setIcon(style, new ImageIcon(image));
	    
	    SimpleAttributeSet attributes = new SimpleAttributeSet();
	    //StyleConstants.setBold(attributes, true);
	    //StyleConstants.setItalic(attributes, true);
	    String s = name + " says: ";

	    try {
	    	doc.insertString(doc.getLength(), s , attributes);
			doc.insertString(doc.getLength(), "Ignore", style);
			set_Text("");
		} catch (BadLocationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}	
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anoy;
    private javax.swing.JButton audioBu;
    private javax.swing.JButton blush;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sendFile;
    private javax.swing.JButton smile;
    private javax.swing.JTextField textField;
    private javax.swing.JTextPane textPanel;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JButton unsure;
    private javax.swing.JList<String> userList;
    private javax.swing.JButton wave;
    private javax.swing.JButton woot;
    private javax.swing.JButton yeh;
    // End of variables declaration//GEN-END:variables
}
